uploads = []
generated = []

[[outputs]]
id = "eQbkfBErKl-GSDR5T5Z96"
uri = "file://JetFixDispatch-GitHubPages.tar.gz"
type = "unspecified"
title = "JetFixDispatch-GitHubPages.tar.gz (fresh build)"

[[outputs]]
id = "3nymc-hlFhUwSLj-I3pVj"
uri = "file://github-actions-setup.tar.gz"
type = "unspecified"
title = "github-actions-setup.tar.gz"
